src/scss/layout/_footer.scss

250314/혜원/ 푸터 위치고정

---

src/components/CreateAccount.jsx
src/components/Modal.jsx
src/scss/abstracts/_mixin.scss
src/scss/abstracts/_variables.scss
src/scss/components/_button.scss
src/scss/pages/_createAccount.scss

Feat/Account Mixin 생성(background), Modal 태그 변경

---

src/App.jsx

Fix. mypage reservation 대체 경로 변경

---

src/scss/components/_button.scss

Fix. 머지에러 수정

---

src/components/Header.jsx
src/scss/layout/_header.scss

- 사용 편의를 위해 페이지를 아래로 스크롤하면 헤더가 사라지도록 구현하였습니다.

Design. 아래로 스크롤시 헤더가 사라지도록 구현

---

src/App.jsx
src/components/Modal.jsx
src/components/Searchbar.jsx
src/pages/SearchResult.jsx
src/scss/components/_button.scss
src/scss/components/_modal.scss
src/scss/components/_searchbar.scss

모달 공통(공용) 컴포넌트입니다.
1. modalRef에는 모달의 useRef를 사용해 dialog요소를 직접 제어할 수 있게 합니다.
2. children에는 모달에 들어갈 내용을 직접 정의합니다. (따로 디자인을 안넣었기 때문에 children의 최상위 div에 스타일을 주시면 컨텐츠 크기가 결정됩니다) 
여기는 모달을 직접 호출하는 공간으로 모달을 여는 것은 필요한 페이지나 컴포넌트에서 useRef를 호출하고 불러야 합니다.
예시 결과 화면 입니다~

25/03/18 승엽 - 모달 공통 컴포넌트 & 캠프사이트 모달 생성

---

src/components/Header.jsx
src/scss/layout/_header.scss

- 로그인 여부에 따라 마이페이지, 로그인 모달을 열 수 있도록 분기를 구현하였습니다
- 로그인 모달 여는 로직은 추가적으로 구현해주시면 됩니다

Feat. 헤더 로그인 분기 구현

---

src/constants/collectionName.js
src/firebaseConfig.js
src/pages/Main.jsx
src/util/fbService.js
src/util/firebaseApi.js

- 모든 데이터를 가져오는 함수 `getAllDocs`
- 쿼리함수 `getQueryDocs`
- ex) 모든 예약 데이터를 가져오는 `getAllReservation` 함수
- ex) 검색 데이터 필터링 `getSearchCampSite` 함수

Feat. firebase 예제 구현

---

package-lock.json
package.json
src/components/DateModal.jsx
src/components/Modal.jsx
src/components/Searchbar.jsx
src/pages/SearchResult.jsx
src/scss/components/_button.scss
src/scss/components/_modal.scss
src/scss/components/_searchbar.scss

지역선택 모달창과 날짜선택 모달창 구현하였습니다.
기존의 달력 라이브러리(shadcn/ui)에서 react-date-range로 변경 후 만들었습니다.
달력 라이브러리에서 현재 날짜를 기준으로 이전 날짜는 선택 못하도록 제한하였습니다.
남은 작업...
1. 데이터 연동
2. 검색 폼 처리
3. 전반적인 검색 결과 페이지 디자인

25/03/18 승엽 - 검색바 & 모달창 디자인(틀) 완료

---

src/components/Searchbar.jsx

Feat. Search 검색바 반복문 수정

---

src/App.jsx
src/components/ItemDetails.jsx
src/components/ProductList.jsx
src/components/ProductListCart.jsx
src/scss/components/_itemlist.scss

itemlist 컴포넌트 
**1. 사용예제** 
- 페이지 주소 **/productListExam**
- ProductListExam.jsx 파일 참고
- 3~4열 배열은 components/_itemlist.scss 하단에 있는 .prodict-list 클래스 참고
- props는 추후 데이터 연동 시 수정 예정
2. components/**ProductList.jsx**
2-1. **/Main** 
- 설정: stock={false}
- 남은 자리가 보이지 않게 처리
2-2. **/SearchResult** 
- 설정: stock={true}
- 남은 자리가 보이게 구현
(남은 작업) 
- 데이터 연동 
- 존재하지 않는 데이터는 보이지 않게 처리(ex 대 자리)
- 재고가 매진됐을 경우 텍스트 색상 변경
3.  components/**ProductListCart.jsx**
3-1. **/Reservation**
- 설정: isRSV={true}, isCart={false}
3-2. **/Cart** 
- 설정: isRSV={false}, isCart={true}
- 특이사항: 체크박스를 기본 체크 상태로 설정 
(장바구니에 들어가면 담겨있는 상품이 기본 체크 상태이고, 예약을 원치 않을 경우 체크 해제하는 식)
(남은 작업) 
- 데이터 연동
- 예약한 startDate가 오늘(기준일)로부터 과거일 경우 [취소 불가] 버튼으로 변경
- 예약한 자리 데이터(selected)만 출력되게 처리
- 각 아이템 클릭 시 상세 페이지로 넘어가게

Feat. itemList 클래스네임 수정

---

src/components/DateModal.jsx
src/components/Searchbar.jsx
src/scss/components/_button.scss
src/scss/components/_searchbar.scss

모달창 다중선택에서 한 개만 선택하도록 수정하였습니다.
날짜 선택도 수정했습니다.

Feat.Search 모달창 선택 수정

---

src/App.jsx
src/components/CreateAccount.jsx
src/components/Login.jsx
src/constants/errorCodes.js
src/pages/Main.jsx
src/scss/components/_input.scss
src/store/useUserStore.js

- Create Account 데이터에서 DB User컬렉션의 변경된 필드명과 코드를 일치하도록 변경했습니다.

DB User 컬랙션의 필드명 변경

---

src/App.jsx
src/components/Searchbar.jsx
src/scss/components/_button.scss
src/scss/components/_searchbar.scss

간격 조정, 검색바 스타일 수정, 버튼 스타일 수정했습니다

Feat/search 검색바 스타일 수정 + 버튼 스타일 수정 

---

src/components/Checkbox.jsx
src/pages/CheckboxExam.jsx
src/scss/components/_checkbox.scss

1. Checkbox 컴포넌트 HTML 구조 변경
변경 전 :
\<label\>	
\<input /\>    
\</label\>
(label 태그 안에 Input 태그 === 웹 접근성 오류)
따라서 구조를 <div> 안에 <input>과 <label> 태그로 분리
변경 후:
\<div\>
\<input /\>
\<label\>\</label\>
\</div\>
2. input 태그 안의  onChange={onClick} -> onChange={onChange}로 변경
추후 작업 사항: 디테일 페이지 추가 작업

Chore. Checkbox 컴포넌트 HTML 구조 변경

---

src/components/Gnb.jsx
src/components/Header.jsx

- header안의 nav를 별도의 컴포넌트로 분리
- 버튼 대신 link컴포넌트로 변경

Fix. gnb 컴포넌트 분리

---

src/components/Header.jsx
src/constants/headerMenus.js

가독성을 위해 헤더 파일에 있던 메뉴 데이터 코드를 별도의 파일로 분리했습니다

Fix. 헤더 메뉴 데이터 분리

---

src/pages/Main.jsx
src/scss/components/_button.scss
src/scss/pages/_main.scss

Button.scss 파일에 중복된 코드 들어간것 수정.

Fix. Button.scss에 중복코드 들어간 부분 수정

---

src/components/Chip.jsx
src/components/DateModal.jsx
src/components/Modal.jsx
src/components/Searchbar.jsx
src/scss/components/_chip.scss
src/store/useSearchStore.js

* 전역으로 검색 부분 상태관리 --> useSearchStore
* 모달 취소 버튼 기능 구현

Feat.search zustand로 검색부분 전역으로 상태 관리

---

src/components/Header.jsx
src/store/useUserStore.js

- 로그아웃시 로컬스토리지 초기화, 스토어 초기화가 이루어집니다.

Feat. 로그아웃 구현

---

src/components/Topbtn.jsx
src/scss/components/_button.scss

##Topbtn.jsx 수정
1. body에서 제대로 작동하지 않는 것 같아서 documentElement로 기준(대상...?)을 바꿨습니다. 👍
2. `_button.scss`에서 버튼 네이밍을 바꿨습니다.
.사용처__기능-btn 형식으로 btn이 뒤에 오는 게 맞는 형식이라고 들어서 일단 top-btn만 바꿔두긴 했는데... 아닐 시 나중에 돌려놓겠습니다 😢
**수정 전**
```jsx
document.body.scrollTo({
top: 0,
behavior: "smooth",
});
```
**수정 후**
```jsx
document.documentElement.scrollTo({
top: 0,
behavior: "smooth",
});
```

Feat.Topbtn / 스크롤 투 탑 수정

---

src/App.jsx
src/components/DateModal.jsx
src/components/MainAllCampsite.jsx
src/components/ProductList.jsx
src/components/SearchBarButton.jsx
src/components/Searchbar.jsx
src/components/SelectBox.jsx
src/pages/SearchResult.jsx
src/scss/components/_button.scss
src/scss/components/_modal.scss
src/scss/components/_searchbar.scss
src/scss/components/_selectBox.scss
src/util/selectors.js

* useParams로 검색을 받고 data를 refetch로 재호출하기 때문에 새로고침을 해도 useParams가 그대로 남아있어 검색 결과가 유지된다
* 검색바 버튼 스타일을 수정하였습니다!!(글자 왼쪽 정렬 + 버튼 사이즈 고정값)

Feat.search 검색바 스타일 수정 + useParams로 검색하기

---

src/App.jsx
src/components/MainAllCampsite.jsx
src/pages/Main.jsx
src/pages/Reservation.jsx
src/store/useSectionRefStore.js

- header의 스크롤 이벤트 구현할때 필요없는 코드를 제거했습니다.
- fallback의 로딩을 제거했습니다

Fix. 불필요한 코드 제거

---

package-lock.json
src/components/MainAllCampsite.jsx
src/components/MainIntro.jsx
src/components/MainMostRSV.jsx
src/components/MainRecommand.jsx
src/components/Searchbar.jsx
src/pages/Main.jsx
src/scss/components/_mainAllCampsite.scss
src/scss/components/_mainMostRSV.scss
src/scss/components/_mainRecommand.scss
src/scss/pages/_main.scss

- MainIntro.jsx  파일에 애니메이션을 적당히(?) 적용했습니다.
- 카드를 클릭하면 이제 Detail 페이지로 이동합니다.
- 자잘한 마크업 유효성 오류들 수정했습니다.
-

Feat/slider  Main 브랜치 머지 요청

---

src/components/DTsiteModal.jsx
src/components/DetailOptionBox.jsx
src/pages/DetailPage.jsx
src/scss/abstracts/_variables.scss
src/scss/components/_searchbar.scss
src/scss/pages/_detailpage.scss
src/store/useSiteStore.js

1. tanstack 쿼리를 사용하여 데이터 관리
1-1. useQuery를 통해 데이터를 가져옴    {data: campData}
1-2. useMutation을 통해 firebase User 컬렉션에 접근해서 값을 업데이트
2. 사용자가 지정한 날짜에 따른 site의 개수를 화면에 보여주기
2-1. 사용자가 지정한 날짜(ex. 2025-04-09 ~ 2025-04-11) 중에서 
날짜 별 site의 개수를 object type으로 변환한 다음 getMinAvailableSites
함수를 통해 가장 작은 값들(minSites)을 리턴
2-2.   const [minAvailable, setMinAvailable] = useState(null);
const minAvailable = getMinAvailableSites(siteCountsByDate);
setMinAvailable(minAvailable); 을 통해 minAvailable값을 props로 DTsiteModal에 전달
2-3. site의 모든 값이 null(allNull)인 경우<br>
2-4. 날짜 선택 전에 자리를 선택한 경우 (날짜 선택 이후 자리를 선택 유도)<br>
2-5. 카라반이 null인 경우<br>

Feat. 상세페이지 구현

---

src/components/ProductList.jsx
src/components/Searchbar.jsx
src/components/SelectBox.jsx
src/pages/SearchResult.jsx
src/scss/base/_typography.scss
src/scss/pages/_searchResult.scss
src/store/useSearchStore.js
src/util/selectors.js

* filterValue(select box)를 설정해 원하는 정렬을 하도록 구현하였습니다.
* productlist.jsx에 motion.div로 애니메이션 효과를 부여했습니다. + Link로 상세페이지 이동이 가능합니다

Feat.search select box 필터링 구현

---

src/components/DetailFacility.jsx
src/components/DetailInfo.jsx
src/components/DetailOptionBox.jsx
src/pages/DetailPage.jsx
src/pages/SearchResult.jsx
src/scss/components/_button.scss
src/scss/pages/_detailpage.scss

* DetailPage scss 수정
* 관련 컴포넌트 스타일 수정

Design/DetailPage 디테일 페이지 + 관련 컴포넌트 스타일 수정

---

src/components/ItemDetails.jsx
src/components/ProductList.jsx
src/pages/DetailPage.jsx
src/scss/components/_detailFacility.scss
src/scss/components/_detailOptionBox.scss
src/scss/components/_index.scss
src/scss/components/_itemlist.scss
src/scss/pages/_detailpage.scss

* 디테일 페이지 스타일 수정
* 검색 시 0자리일 경우 빨간색 표시 및 productList 남은 자리 스타일 수정

Feat.search 0자리 매진 표시 + 디테일 페이지 수정

---

src/util/fbService.js
src/util/firebaseApi.js
src/util/util.js

- 함수이름을 insert로 잘못써서 update로 수정하였습니다
- `monthDateFormat`함수에서 날짜데이터가 null인경우, 월,일로 변경하지 않고 "-"로 리턴
- User컬렉션 안에 장바구니 배열에 날짜데이터가 null로 잘못 들어가있는 경우를 제거했습니다.

Fix. 잘못된 함수이름 수정, 장바구니에 날짜데이터가 null인경우 대응

---

src/components/ConfirmModal.jsx
src/components/DetailFacility.jsx
src/pages/DetailPage.jsx
src/scss/components/_detailFacility.scss
src/scss/layout/_baselayout.scss
src/scss/pages/_detailpage.scss

1. 스타일 폰트 적용 및 css 수정
2. 장바구니 보기 모달 링크 생성
3. 승엽님 전달 사항
내일 Available_RSV에 'intro' 데이터 넣어주시면 감사하겠습니다! 
{campData.featureNm || campData.intro} 소개에 들어갈 내용을 위한 데이터

Design. detail 페이지 디자인 수정 및 링크 연결

---

package-lock.json
package.json
src/App.jsx
src/components/Gnb.jsx
src/components/MainAllCampsite.jsx
src/components/MainMostRSV.jsx
src/components/MainRecommand.jsx
src/main.jsx
src/pages/Account.jsx
src/pages/MyPage.jsx
src/pages/SearchResult.jsx
src/scss/components/_gnb.scss
src/scss/pages/_account.scss
src/scss/pages/_createAccount.scss
src/scss/pages/_index.scss

Feat/avatar DevTools Setting

---

package-lock.json
src/App.jsx
src/components/NoResult.jsx
src/components/ProductList.jsx
src/components/SelectBox.jsx
src/pages/SearchResult.jsx
src/scss/components/_noResult.scss
src/scss/components/_selectBox.scss
src/scss/pages/_searchResult.scss
src/store/useSearchStore.js

* 검색 수정(데이터 바꾸고 나서 오류 수정)
* 디자인 수정 searchResult페이지(Feat. 혜원님)
* selectBox 공통 컴포넌트화

Fix.Search 검색과 디자인 수정

---

src/pages/Cart.jsx
src/scss/components/_button.scss
src/scss/pages/_cart.scss

Design. 장바구니 디자인 수정

---

src/components/ProductList.jsx
src/pages/Cart.jsx
src/util/util.js

- string인 경우 toString 수행하지 않도록 수정

Design/cart: 가격에 세자리단위로 콤마를 찍는 함수 수정

---

src/components/MainRecommand.jsx
src/scss/components/_mainAllCampsite.scss
src/scss/pages/_main.scss

Design.Baselayout / 띄어쓰기, 마진 수정

---

src/components/MyPageAside.jsx

- path가 변경될때마다 active되는 메뉴를 다시 set하도록 변경했습니다.

Fix. 결제 후 마이페이지 aside의 active가 잘못 표시되는 문제 수정

---

src/pages/Reservation.jsx
src/scss/pages/_reservation.scss

Feat/Reservation 컴포넌트 배열 수정

---

src/App.jsx
src/pages/Account.jsx
src/pages/CreateAccount.jsx
src/pages/MainPage.jsx
src/scss/pages/_account.scss
src/util/fbService.js

- 회원정보를 수정하는 기능을 구현.  (닉네임, 프로필 이미지만 변경 가능.)
- 회원 탈퇴 기능을 구현. (Reservation Collection, User Collection  UserAuth, Zustand Data초기화)

Feat. 회원정보 수정, 삭제 기능 구현 완료.

---

src/components/DTsiteModal.jsx
src/components/MyPageAside.jsx
src/components/Searchbar.jsx
src/layout/MyPageContentLayout.jsx
src/pages/Cart.jsx
src/pages/DetailPage.jsx
src/pages/MyPage.jsx
src/pages/Reservation.jsx
src/scss/components/_button.scss
src/util/fbService.js
src/util/firebaseApi.js
src/util/reservationService.js
src/util/util.js

- 모달 여는함수, 닫는함수 공용함수로 만들어 사용
- 함수는 util폴더 안에 있습니다
- service함수들에 에러처리가 누락되어 추가하였습니다

Refactor/functions: 리팩토링

---

src/components/Header.jsx
src/pages/Cart.jsx
src/scss/components/_headerSelect.scss
src/scss/components/_selectBox.scss
src/scss/pages/_detailpage.scss

* 장바구니 user이름으로 보이게 하기
* 헤더 올라가면 커스텀 selectBox 올라가기
* 커스텀 selectBox 애니메이션 추가

Desing/SelectBox 커스텀Select 애니메이션 추가 및 장바구니 이름 보이기

---

package-lock.json
src/components/DetailOptionBox.jsx
src/pages/DetailPage.jsx
src/util/firebaseApi.js

const { data: campData } = useQuery({
queryKey: ["campSite", id],
queryFn: async () => {
const matchedId = await fBService.getCampsiteData(id);
return matchedId[0].data;
},
enabled: !!id,
});
fBService.getCampsiteData api 활용

Fix. 데이터 fetch 변경

---

src/pages/Cart.jsx

- 장바구니 배열의 길이가 1개여도 삭제 가능하도록 수정

Fix. 장바구니 삭제로직 수정

---

src/pages/Account.jsx
src/pages/CreateAccount.jsx
src/pages/DetailPage.jsx
src/scss/layout/_header.scss
src/scss/pages/_createAccount.scss
src/scss/pages/_login.scss
src/util/firebaseApi.js

- 회원가입 Form 에서의  비밀번호 토글버튼 (눈알)  스타일 버그나는것 수정.
- 회원가입 Form 전체적 스타일 조정.

Fix. 회원가입 Form  토글버튼 오류 수정

---

src/pages/Reservation.jsx

- 예약 내역이 없을 때 레이아웃이 깨지는 현상 수정✌

Fix.Reservation page 예약 내역 수정

---

src/pages/Cart.jsx

Design. 장바구니 페이지 폰트 적용

---

src/components/MainIntro.jsx
src/util/firebaseApi.js

Design. 이미지 경로 변경

---

src/components/Header.jsx
src/components/MainRecommand.jsx
src/pages/Account.jsx

Fix/Header 이미지 경로 수정

---

src/components/ProductList.jsx
src/util/util.js

Fix. 콤마찍는 함수에서 number가 null인경우 수정

---

src/components/MainAllCampsite.jsx
src/components/MainIntro.jsx
src/components/MainMostRSV.jsx
src/components/MainRecommand.jsx
src/components/ProductCard.jsx
src/components/ProductList.jsx
src/components/ProductListCart.jsx
src/pages/Login.jsx
src/scss/layout/_header.scss
src/scss/pages/_main.scss
src/util/firebaseApi.js
vercel.json

- 헤더 Avatar 이미지를  6rem ~> 4rem 으로 변경했습니다.
- vercel.json 파일을 생성했습니다. 서브페이지 이동 관련 오류가 생길 경우를 대비함입니다.
```javascript
{
"rewrites": [{ "source": "/(.*)", "destination": "/" }]
}
``` 
- mainIntro.jsx 페이지의  img 태그안의 alt 속성을 제거했습니다.
- product,  productList,  productListCart   파일의 img 파일안에  alt 속성을 넣어주었습니다.

Fix. 오후 피드백 받은 부분들 수정

---

src/pages/Cart.jsx
src/scss/components/_modal.scss

- 장바구니 페이지에서 아이템 클릭 후 상세페이지로 이동
- 환불규정 및 약관동의 폰트키움

Fix/cart: 장바구니 페이지 피드백 반영

---

src/components/Header.jsx
src/components/Logo.jsx
src/scss/components/_logo.scss
src/scss/layout/_header.scss

- header에서 h1안에 a>img로 변경
- 주석처리된 코드 제거

Fix. header수정 및 불필요한 코드 제거

---

src/App.jsx
src/pages/MyPage.jsx

- 마이페이지에 로그인하지 않고 접근했을 때, 메인페이지로 바로 navigate하도록 구현하였습니다.

Feat. 마이페이지 로그인 안했을 때 접근 못하도록 처리

---

src/pages/Reservation.jsx

* (멘토님 피드백 반영) ProductListCart에 받아오는 props 한 번에 전달
**수정 전**
```jsx
<ProductListCart
firstImageUrl={reservation.data.firstImageUrl}
startDate={monthDateFormat(reservation.data.rsvStartDate)}
endDate={monthDateFormat(reservation.data.rsvEndDate)}
day={getDaysBetweenDates(
reservation.data.rsvStartDate,
reservation.data.rsvEndDate
)}
facltNm={reservation.data.facltNm}
selected1={reservation.data.rsvSiteS}
selected2={reservation.data.rsvSiteM}
selected3={reservation.data.rsvSiteL}
selected4={reservation.data.rsvSiteC}
sumPrice={reservation.data.rsvTotalPrice}
isRSV
isDisabled={isDisabled}
buttonText={buttonText}
onCancelClick={(event) => {
event.stopPropagation(); // 버튼 클릭 시 Link 이벤트 전파 방지
event.preventDefault(); // Link 이동 막기
handleCancelClick(reservation.id);
}}
/>
```
**수정 후**
```jsx
const …
```

Fix.Reservation / ProductListCart-props 수정 / 0402 혜원

---

src/components/Header.jsx
src/components/Searchbar.jsx
src/pages/MainPage.jsx
src/scss/components/_searchbar.scss

Feat. 헤더 검색버튼 클릭해서 스크롤 이동시 검색바 focus 구현

---

src/components/DTsiteModal.jsx
src/components/DetailOptionBox.jsx
src/components/Header.jsx
src/components/ProductList.jsx
src/components/ProductListCart.jsx
src/components/Searchbar.jsx
src/pages/Account.jsx
src/pages/Cart.jsx
src/pages/DetailPage.jsx
src/pages/Reservation.jsx
src/scss/components/_button.scss
src/util/dateUtil.js
src/util/modalUtil.js

* util 함수 분리
* 스크롤 올려도 헤더 1초있다 보이기
* 검색 결과 0자리 빨간색으로 처리
* account svg파일 삭제
* disabled 버튼 not allowed처리

Fix.Search util분리, 헤더변경

---

src/components/Footer.jsx
src/scss/layout/_footer.scss

* `motion`과 `useLocation`을 사용해서 푸터를 바닥에 고정했습니다.
* 스크롤 유무나 페이지 이동에 따라 푸터가 알맞게 적용되도록 `useLocation`을 사용했습니다.

Fix.Footer / 푸터 바닥에 고정

---

src/components/Checkbox.jsx

Fix. Link태그 하위의 checkbox가 있는경우, checkbox가 클릭이 되지 않는 문제 수정

---

src/components/Footer.jsx

* 새로고침하거나 페이지 이동 시 푸터가 바닥에 있지 않고 화면에 보이는 현상 수정
* 로딩 후 푸터가 보이도록 조절했습니다.

Fix.Footer / 스크롤 길이에 따른 푸터 기습 출현 해결

---

src/pages/Account.jsx
src/scss/pages/_mypageContentLayout.scss

Fix. 정보변경 페이지 정렬 문제 수정

---

src/components/DetailFacility.jsx
src/components/Footer.jsx
src/components/MainRecommand.jsx
src/components/Topbtn.jsx
src/pages/Account.jsx
src/pages/Cart.jsx
src/pages/CreateAccount.jsx
src/pages/Login.jsx
src/pages/Reservation.jsx
src/pages/SearchResult.jsx
src/scss/abstracts/_variables.scss
src/scss/layout/_index.scss
src/scss/pages/_createAccount.scss
src/store/mypageTitleStore.js
src/util/fbService.js
src/util/reservationService.js
src/util/selectors.js

- 배포를 위해 개발중 사용했던 콘솔로그 구문을 주석처리했습니다

Fix. 콘솔로그 주석처리

---

src/constants/errorCodes.js
src/pages/Account.jsx

- account.jsx 페이지에 onValid 함수 내 사용자 인증 추가 과정을 넣었습니다.
- 비밀번호 input을 다시 살렸습니다. 이제 사용자가 정확한 비밀번호를 다시 입력해야 정보 변경이 이루어집니다.

Feat. 정보변경 시 사용자 재인증과정 추가

---

src/components/Footer.jsx
src/components/Loading.jsx
src/components/MainRecommand.jsx
src/components/Searchbar.jsx
src/pages/Cart.jsx
src/pages/DetailPage.jsx
src/scss/components/_selectBox.scss

- 스크롤이 없을때 footer가 보이게 되어있어서, 최상단일때도 footer가 보이는 문제가 있어 수정했습니다.
- 아이콘에서는 rem이 적용이 안되는 문제를 간과하여.. 도로 px값으로 돌려놓았습니다.
- 기타 불필요한 코드를 제거하고 주석을 달았습니다.

Fix. 작은 UI 오류들 수정

---

src/pages/DetailPage.jsx

Fix. cart에 장바구니 내용 push

---

src/components/MainMostRSV.jsx

메인페이지 캐러셀 슬라이드가 마지막 1장까지 보이던걸 총 3장으로 제한을 뒀습니다.

Fix. 메인 캐러셀 총 3장으로 제한

---

src/components/ProductListCart.jsx
src/scss/components/_button.scss

Fix. 예약 취소하기 버튼 cursor 잘못 표시되는 문제 수정

---

src/pages/Cart.jsx

- 장바구니 결제시에 zustand state에서도 해당 데이터가 제거되도록 수정했습니다.

Fix. 장바구니 결제시 state에서도 결제된 데이터 제거
